### PR TITLE
fix: Tab inside an editable field should trigger keyboard mode

### LINKED ISSUE #50: Any keypress from editable elements does not set keyboard navigation mode
https://github.com/microsoft/keyborg/blob/197b994e8cb7a887a19e025c01f49db802d1e0e0/src/Keyborg.ts#L244-L253

The current keyboard navigation check is done so that any keypress (even ones explicitly set by the user) will not trigger keyboard navigation mode. This results in keys like `Tab` not triggering keyboard navigation mode:

Repro: https://codesandbox.io/p/sandbox/laughing-julien-fzkln2?file=%2Fsrc%2Fexample.tsx
1. Click on the input
2. Press tab
3. First button does not have a focus outline

### PR DESCRIPTION
**Pull request by ling1726**
Tab key should still trigger keyboard navigation when inside an editable field. There is still an unknown edge case where rich text fields could use Tab key to indent - however we should handle that case if it ends up resulting in any bugs.

Also cleans up the conditions to trigger/dismiss keyboard navigation mode.

Fixes #50

### CODE REVIEW

File: src/Keyborg.ts [hunk 1]
```diff
@@ -229,35 +229,47 @@ class KeyborgCore implements Disposable {
...
+
+    const activeElement = this._win?.document
+      .activeElement as HTMLElement | null;
+    const isTriggerKey = !this._triggerKeys || this._triggerKeys.has(e.keyCode);
+
+    const isEditable =
+      activeElement &&
+      (activeElement.tagName === "INPUT" ||
+        activeElement.tagName === "TEXTAREA" ||
+        activeElement.contentEditable === "true");
```
Comment (layershifter) [inline src/Keyborg.ts:261]:
```suggestion
        activeElement.isContentEditable);
```

`contentEditable` does different thing, https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable

File: tests/focus-behavior.stories.tsx [hunk 2]
```diff
@@ -21,3 +21,18 @@ export const Buttons = () => (
     <KeyboardMode />
   </div>
 );
+
+export const Input = () => (
+  <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
+    <h1>Focus Behavior with Buttons</h1>
```
Comment (layershifter) [inline tests/focus-behavior.stories.tsx:27]:
```suggestion
    <h1>Focus Behavior with input</h1>
```

**Review by layershifter — APPROVED** [review]
